import { makeStyles } from '@material-ui/core/styles';

const heroHeight = 750;
const topOffset = 50;

export default makeStyles((theme) => ({
  heroBox: {
    height: heroHeight,
    width: '68%',
    backgroundColor: '#5B5B5B',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    position: 'relative',
  },
  whiteBox: {
    height: heroHeight,
    width: '32%',
    backgroundColor: 'white',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  heroText: {
    color: 'white',
    whiteSpace: 'nowrap',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    position: 'absolute',
    width: 'auto',
    marginRight: 340,
  },
  seeWorkBtn: {
    marginTop: 16,
    color: '#00D3FF',
    borderColor: '#00D3FF',
  },
  topCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 215 - topOffset,
    left: '67.89%',
    zIndex: 1,
  },
  topRightCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 270 - topOffset,
    left: '67.86%',
    zIndex: 2,
  },
  topLeftCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 270 - topOffset,
    right: '31.86%',
    zIndex: 2,
  },
  rightCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 400 - topOffset,
    left: '67.89%',
    zIndex: 2,
  },
  leftCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 400 - topOffset,
    right: '31.86%',
    zIndex: 2,
  },
  bottomRightCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 500 - topOffset,
    left: '67.86%',
    zIndex: 1,
  },
  bottomLeftCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 500 - topOffset,
    right: '31.86%',
    zIndex: 1,
  },
  bottomRightSmallCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 625 - topOffset,
    left: '67.86%',
    zIndex: 1,
  },
  bottomLeftSmallCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 625 - topOffset,
    right: '31.86%',
    zIndex: 1,
  },
  rightRightCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 460 - topOffset,
    left: '67.89%',
    zIndex: 3,
  },
  leftLeftCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 460 - topOffset,
    right: '31.86%',
    zIndex: 3,
  },
  leftLeftTopCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 345 - topOffset,
    right: '31.86%',
    zIndex: 1,
  },
  leftSmallTopCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 365 - topOffset,
    right: '31.86%',
    zIndex: 0,
  },
  leftSmallBottomCube: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    top: 550 - topOffset,
    right: '31.86%',
    zIndex: 4,
  },
}));